### ISSUE TITLE
A template function can only have 10 parameters

### ISSUE THREAD

**Issue by dizzzz** [eXist-db/shared-resources#15]
original posting in  https://github.com/eXist-db/exist/issues/505

**Comment by jensopetersen** [comment]
To summarize: on May 26, 2013 15 parameters were made possible in templates:call-with-args(), but this change was mirrored in templates:resolve(), which still limited the arity to 10. This was fixed Sep 12, 2014 in https://github.com/eXist-db/shared-resources/commit/5416566d61b296873e7e1627dc36840aa0213bd2, but this commit was too late to be included in the xar that is the latest at the present time, since it is from 2014-07-21. This means that it is still the case, with a standard installation, that only 10 parameters are possible. What is needed is therefore an up-to-date xar.

**Comment by joewiz** [comment]
Closed by https://github.com/eXist-db/shared-resources/pull/29
